openapi: 3.0.1
info:
  title: ExternalSupplierCallBackAPI
  description: API Definition of ExternalSupplierCallBackAPI
  version: 1.0.0
servers:
- url: http://localhost:8290/checkStatus
paths:
  /:
    get:
      responses:
        default:
          description: Default response
